baseURL = "https://josh.feiermanfamily.com"
languageCode = "en-us"
title = "Josh Feierman's Website"

[taxonomies]
  tag = "tags"

[permalinks]
  blog = "/:filename/"

[outputs]
  home = ["HTML", "RSS"]

[outputFormats.RSS]
  mediaType = "application/rss+xml"
  baseName = "rss"

[params]
  tagline = "Passionate tool maker and open source enthusiast"
  description = "The website of Josh Feierman, experienced cloud and data professional, tech geek and lover of good beer and sci-fi."
  copyright = "Â© 2019 Josh Feierman, All rights reserved"

[params.author]
  name = "JOSH FEIERMAN"
  bio = "Self-taught cloud and data afficionado, lover of fine beer, bourbon, science fiction."

[params.author.contacts]
  linkedin = "https://www.linkedin.com/in/joshuafeierman/"
  github = "https://github.com/yardbirdsax"
  medium = "https://medium.com/@yardbirdsax"
  twitter = "https://twitter.com/awanderingmind"

[[params.labels]]
  tag = "azure"
  tech = "Azure"
  name = "FaWindows"
  size = 20
  color = "deepskyblue"

[[params.labels]]
  tag = "git"
  tech = "Git"
  name = "DiGitMerge"
  size = 20
  color = "white"

[[params.labels]]
  tag = "python"
  tech = "Python"
  name = "DiPython"
  size = 20
  color = "deepskyblue"

[[params.labels]]
  tag = "aws"
  tech = "AWS"
  name = "FaAws"
  size = 20
  color = "yellow"

[markup]
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'monokai'
    tabWidth = 4

# Deployment configuration for AWS S3
[deployment]
  [[deployment.targets]]
    name = "production"
    URL = "s3://josh.feiermanfamily.com?region=us-east-1"

  [[deployment.matchers]]
    # Cache static assets for 1 year
    pattern = "^.+\\.(js|css|svg|ttf|woff|woff2|eot|png|jpg|jpeg|gif|ico)$"
    cacheControl = "max-age=31536000, no-transform, public"
    gzip = true

  [[deployment.matchers]]
    # Set default cache control for HTML files
    pattern = "^.+\\.(html|xml|json)$"
    cacheControl = "max-age=0, no-cache, no-store, must-revalidate"
    gzip = true
